core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class QuestionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(pub_date__lte=timezone.now())


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = QuestionManager()

    def __str__(self):
        return self.question_text
    
    def get_absolute_url(self):
        return reverse("polls:detail", kwargs={"question_id": self.pk})
    

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="question_choices", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from polls.models import Choice, Question


def index(request):
    questions = Question.objects.order_by('-pub_date')
    return render(request, 'polls/index.html', {'questions': questions})


def detail(request, question_id):
    try:
        question = Question.objects.prefetch_related('question_choices').get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})


def vote(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        selected_choice = question.question_choices.get(pk=request.POST['choice'])
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })

    selected_choice.votes += 1
    selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    try:
        question = Question.objects.prefetch_related('question_choices').get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/results.html', {'question': question})

polls/templates/polls/detail.html
{% extends 'app.html' %} {% block content %}
<h1>{{ question.question_text }}</h1>

<form
  class="question-form"
  action="{% url 'polls:vote' question.id %}"
  method="post"
>
  {% csrf_token %}
  <fieldset class="question-form-fieldset">
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %} {% for choice in question.question_choices.all %}
    <div class="form-input">
      <input
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
      />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
      ><br />
    </div>
    {% endfor %}
  </fieldset>
  <button class="form-btn" type="submit">Vote</button>
</form>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'app.html' %} {% block content %} {% if questions %}
<ul>
  {% for question in questions %}
  <li class="question">
    {{forloop.counter}}.
    <a href="{% url 'polls:detail' question.id %}"
      >{{ question.question_text }}</a
    >
    <span class="pub_date">{{question.pub_date}}</span>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} {% endblock content %}

polls/templates/polls/results.html
{% extends 'app.html' %} {% block content %}
<h1>{{ question.question_text }}</h1>

<ul class="choices">
  {% for choice in question.question_choices.all %}
  <li class="question-choice">
    {{forloop.counter}}. {{ choice.choice_text }} -- {{ choice.votes }} vote{{
    choice.votes|pluralize }}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

templates/app.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <header class="header">
      <a href="{% url 'polls:index' %}" class="logo">
        <img src="{% static 'logo.png' %}" alt="" />
      </a>
      <div class="header-right">
        <a href="{% url 'polls:index' %}">Questions</a>
      </div>
    </header>

    <main>{% block content %}{% endblock content %}</main>

    <footer>
      <img src="{% static 'logo.png' %}" alt="" />
      <div>
        &#169; Made by Tural Hasanov, Fachhochschule Dortmund {% now 'Y' %}. All
        rights reserved.
      </div>
    </footer>
  </body>
</html>